import type { Conductor, Hand, Verdict } from '@ydi/contracts';

type Player = string;
export type GameState = { roomId: string; players: [Player, Player]; version: number; round: number; hands: Record<Player, Hand>; selections: Record<Player, string[]>; usedCharacterIds: Record<Player, string[]>; usedTraitIds: Record<Player, string[]>; characterState: Record<string, { traitIds: string[]; arguments: Array<{ kind: 'attack' | 'defense'; text: string }> }>; conductor: Conductor; debate: null | { attacker: Player; defender: Player; targetId: string; attack: string; defense?: string }; lastVerdict: Verdict | null };

export function createGame(roomId: string, players: [Player, Player], hands: Record<Player, Hand>, conductor: Conductor): GameState { return { roomId, players, version: 1, round: 1, hands, selections: Object.fromEntries(players.map((p) => [p, []])), usedCharacterIds: Object.fromEntries(players.map((p) => [p, []])), usedTraitIds: Object.fromEntries(players.map((p) => [p, []])), characterState: {}, conductor, debate: null, lastVerdict: null }; }
const bump = (game: GameState, update: Partial<GameState>): GameState => ({ ...game, ...update, version: game.version + 1 });
export function selectCharacters(game: GameState, player: Player, ids: string[]) { if (game.selections[player]?.length) throw new Error('characters already selected'); if (ids.length !== 2 || new Set(ids).size !== 2) throw new Error('select exactly two characters'); const available = game.hands[player]?.characters.filter((c) => !game.usedCharacterIds[player]?.includes(c.id)).map((c) => c.id) ?? []; if (ids.some((id) => !available.includes(id))) throw new Error('character does not belong to player or was used'); return bump(game, { selections: { ...game.selections, [player]: [...ids] }, usedCharacterIds: { ...game.usedCharacterIds, [player]: [...(game.usedCharacterIds[player] ?? []), ...ids] }, characterState: { ...game.characterState, ...Object.fromEntries(ids.map((id) => [id, game.characterState[id] ?? { traitIds: [], arguments: [] }])) } }); }
export function autoSelectCharacters(game: GameState, player: Player) { const ids = game.hands[player]!.characters.map(({ id }) => id).filter((id) => !game.usedCharacterIds[player]!.includes(id)).sort().slice(0, 2); return selectCharacters(game, player, ids); }
export function attachTrait(game: GameState, player: Player, traitId: string, targetId: string) { const trait = game.hands[player]?.traits.find((x) => x.id === traitId); if (!trait || game.usedTraitIds[player]?.includes(traitId)) throw new Error('trait unavailable'); if (!Object.values(game.selections).flat().includes(targetId)) throw new Error('target is not on the field'); const state = game.characterState[targetId] ?? { traitIds: [], arguments: [] }; return bump(game, { usedTraitIds: { ...game.usedTraitIds, [player]: [...game.usedTraitIds[player]!, traitId] }, characterState: { ...game.characterState, [targetId]: { ...state, traitIds: [...state.traitIds, traitId] } } }); }
export function submitAttack(game: GameState, attacker: Player, targetId: string, text: string) { if (game.debate) throw new Error('attack already submitted'); if (text.length > 2000) throw new Error('speech too long'); const defender = game.players.find((p) => p !== attacker)!; if (!game.selections[defender]?.includes(targetId)) throw new Error('invalid target'); return bump(game, { debate: { attacker, defender, targetId, attack: text } }); }
export function submitDefense(game: GameState, defender: Player, text: string) { if (!game.debate || game.debate.defender !== defender || game.debate.defense !== undefined) throw new Error('defense unavailable'); if (text.length > 2000) throw new Error('speech too long'); return bump(game, { debate: { ...game.debate, defense: text } }); }
export function applyVerdict(game: GameState, verdict: Verdict) { if (!game.debate || game.debate.defense === undefined) throw new Error('debate incomplete'); const target = game.characterState[game.debate.targetId]!; return bump(game, { lastVerdict: verdict, characterState: { ...game.characterState, [game.debate.targetId]: { ...target, arguments: [...target.arguments, { kind: verdict.winner, text: verdict.coreArgument }] } } }); }
